/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ForeignTransactionsSchema {
  type: {
    metadata: {
      messages: {
        messageDescription: string;
        messageCode: 11040;
        severity: 'I';
      }[];
      links: {};
    };
    formattedValidityDate: {
      [k: string]: unknown;
    };
    outputArrayRecordSum2: {
      [k: string]: unknown;
    };
    displayedRevaluationCurrencyCode: {
      [k: string]: unknown;
    };
    rateFixingDescription: {
      [k: string]: unknown;
    };
    currancyBalanceData: {
      [k: string]: unknown;
    };
    currencyCode: {
      [k: string]: unknown;
    };
    balancesAndTransactionsCurrencyCombo: {
      currencyCode: {
        [k: string]: unknown;
      };
    };
    detailedAccountTypeCode: {
      [k: string]: unknown;
    };
    foreignCurrencyBalancesData: {
      [k: string]: unknown;
    };
    balancesAndLimitsDataList: {
      numItemsPerPage: number;
      transactionResultCode: number;
      detailedAccountTypeCode: 142;
      currencyCode: number;
      withdrawalBalance: {
        [k: string]: unknown;
      };
      currentBalance: {
        [k: string]: unknown;
      };
      lastBalance: {
        [k: string]: unknown;
      };
      lastEventDate: {
        [k: string]: unknown;
      };
      formattedLastEventDate: {
        [k: string]: unknown;
      };
      outputArrayRecordSum3: {
        [k: string]: unknown;
      };
      outputArrayRecordSum4: {
        [k: string]: unknown;
      };
      revaluatedCurrentBalance: [];
      rateExerciseDescription: {
        [k: string]: unknown;
      };
      currentBalanceExchangeRateWayDescription: {
        [k: string]: unknown;
      };
      currentBalanceExchangeRateWayCode: {
        [k: string]: unknown;
      };
      rateRealizationCode: {
        [k: string]: unknown;
      };
      lastBalanceExchangeRateWayCode: {
        [k: string]: unknown;
      };
      bankNumber: {
        [k: string]: unknown;
      };
      branchNumber: number;
      accountNumber: number;
      retrievalMinDate: number;
      formattedRetrievalMinDate: string;
      retrievalMaxDate: number;
      formattedRetrievalMaxDate: string;
      creditLimits: string[];
      transactions: {
        metadata: {
          attributes: {
            originalEventKey?: {
              hidden?: {
                [k: string]: unknown;
              };
              disabled?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            contraBranchNumber?: {
              hidden?: {
                [k: string]: unknown;
              };
              disabled?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            contraAccountNumber?: {
              hidden?: {
                [k: string]: unknown;
              };
              disabled?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            contraBankNumber?: {
              hidden?: {
                [k: string]: unknown;
              };
              disabled?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            contraAccountFieldNameLable?: {
              hidden?: {
                [k: string]: unknown;
              };
              disabled?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            dataGroupCode?: {
              hidden?: {
                [k: string]: unknown;
              };
              disabled?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            currencyRate?: {
              hidden?: {
                [k: string]: unknown;
              };
              disabled?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            contraCurrencyCode?: {
              hidden?: {
                [k: string]: unknown;
              };
              disabled?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            rateFixingCode?: {
              hidden?: {
                [k: string]: unknown;
              };
              disabled?: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
          links: {};
          [k: string]: unknown;
        };
        executingDate: number;
        formattedExecutingDate: string;
        valueDate: number;
        formattedValueDate: string;
        originalSystemId: number;
        activityDescription: string;
        eventAmount: number;
        currentBalance: number;
        referenceCatenatedNumber: number;
        referenceNumber: number;
        currencyRate: number;
        eventDetails: string | null;
        rateFixingCode: number;
        rateFixingDescription: string;
        contraCurrencyCode: 0 | 1 | 19 | 78 | 100;
        eventActivityTypeCode: number;
        transactionType: string;
        rateFixingShortDescription: string;
        currencyLongDescription: string;
        activityTypeCode: number;
        eventNumber: number;
        validityDate: number;
        comments: {
          [k: string]: unknown;
        };
        commentExistenceSwitch: {
          [k: string]: unknown;
        };
        accountName: string | null;
        contraBankNumber: number;
        contraBranchNumber: number;
        contraAccountNumber: number;
        originalEventKey: {
          [k: string]: unknown;
        };
        contraAccountFieldNameLable: string | null;
        dataGroupCode: {
          [k: string]: unknown;
        };
        recordSerialNumber: number;
        expendedExecutingDate: string;
        urlAddress: {
          [k: string]: unknown;
        };
        currencySwiftCode: string;
      }[];
      messages: string[];
      currencySwiftDescription: string;
      currencyShortedDescription: string;
      pendingBalance: {
        [k: string]: unknown;
      };
      currentAccountLimitsAmount: {
        [k: string]: unknown;
      };
      currencySwiftCode: string;
      currencyLongDescription: string;
      detailedAccountTypeShortedDescription: string;
    }[];
    messages: {
      [k: string]: unknown;
    };
    pdfUrl: {
      [k: string]: unknown;
    };
    validityDate: {
      [k: string]: unknown;
    };
  };
}
